services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: ".env"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../../Back/2026_1_WHITECROWSOFT/migrations:/docker-entrypoint-initdb.d
      - ./../../Back/2026_1_WHITECROWSOFT/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - noterian_network

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file: ".env"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${MINIO_API_PORT}/minio/health/live",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - noterian_network

  attachments:
    build:
      context:  ./../../Back/2026_1_WHITECROWSOFT
      dockerfile: ./../../Back/2026_1_WHITECROWSOFT/cmd/attachments/Dockerfile.attachments
    restart: unless-stopped
    env_file: ".env"
    expose:
      - "${ATTACHMENTS_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - noterian_network

  notes:
    build:
      context:  ./../../Back/2026_1_WHITECROWSOFT
      dockerfile: ./../../Back/2026_1_WHITECROWSOFT/cmd/notes/Dockerfile.notes
    restart: unless-stopped
    env_file: ".env"
    expose:
      - "${NOTES_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - noterian_network

  profiles:
    build:
      context:  ./../../Back/2026_1_WHITECROWSOFT
      dockerfile: ./../../Back/2026_1_WHITECROWSOFT/cmd/profiles/Dockerfile.profiles
    restart: unless-stopped
    env_file: ".env"
    expose:
      - "${PROFILES_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - noterian_network

  main:
    build:
      context:  ./../../Back/2026_1_WHITECROWSOFT
      dockerfile: ./../../Back/2026_1_WHITECROWSOFT/cmd/main/Dockerfile.main
    restart: unless-stopped
    env_file: ".env"
    expose:
      - "${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      attachments:
        condition: service_started
      notes:
        condition: service_started
      profiles:
        condition: service_started
    networks:
      - noterian_network
    
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    depends_on:
      - main
      - attachments
      - notes
      - profiles
    networks:
      - noterian_network

volumes:
  postgres_data:
  minio_data:

networks:
  noterian_network:
    driver: bridge
    