services:
  backend:
    image: ghcr.io/go-park-mail-ru/2026_1_whitecrowsoft:main
    restart: unless-stopped
    env_file: '.env'
    expose:
      - '${PORT}'

  frontend:
    build: .
    # image: ghcr.io/frontend-park-mail-ru/2026_1_whitecrowsoft:latest
    restart: unless-stopped
    env_file: '.env'
    ports:
      - '${PORT_FRONT}:80'
    depends_on:
      - backend
